#!/bin/sh

# Variables controlling training execution.
base_container_uri="gcr.io/smle-enterprise-hackathon/cloudai-autogenerated/wandb:latest"
machine_type="n1-standard-4"
accelerator_type="NVIDIA_TESLA_T4"
accelerator_count=1
package_path="."
script="train.py"
region="us-central1"
display_name="test"
dataset="div2k:latest"
args="${dataset}"

gcloud ai custom-jobs create \
  --region=$region \
  --display-name=$display_name \
  --args="$args" \
  --worker-pool-spec=machine-type=$machine_type,accelerator-type=$accelerator_type,accelerator-count=$accelerator_count,executor-image-uri=$base_container_uri,local-package-path=$package_path,script=$script \
